CREATE TABLE IF NOT EXISTS mpa (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    description   VARCHAR(200),
    release_date  DATE NOT NULL,
    duration      INTEGER CHECK (duration > 0),
    mpa_id        INTEGER REFERENCES mpa (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(200) NOT NULL,
    login         VARCHAR(50) NOT NULL,
    name          VARCHAR(100),
    birthday      DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id       BIGINT  NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    genre_id      INTEGER NOT NULL REFERENCES genres (id) ON DELETE RESTRICT,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id       BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    user_id       BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id       BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    friend_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    approved      BOOLEAN,
    PRIMARY KEY (user_id, friend_id)
);